// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbO4PWzVbAdZFshNvTn_-NyThW_Ac2pQU',
    appId: '1:420842222143:web:1300fd3105d8da3da33e8a',
    messagingSenderId: '420842222143',
    projectId: 'task-ea0a9',
    authDomain: 'task-ea0a9.firebaseapp.com',
    storageBucket: 'task-ea0a9.appspot.com',
    measurementId: 'G-YT35RVKJR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQgR1FKbPLq1fNhD7DBg7eQQOveCSwgKc',
    appId: '1:420842222143:android:229a5e5ec074dffaa33e8a',
    messagingSenderId: '420842222143',
    projectId: 'task-ea0a9',
    storageBucket: 'task-ea0a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzy8pBnnpTXAIFfbMyAfPr3zfh_YHcPxY',
    appId: '1:420842222143:ios:9e2c2713fd74a2f6a33e8a',
    messagingSenderId: '420842222143',
    projectId: 'task-ea0a9',
    storageBucket: 'task-ea0a9.appspot.com',
    iosBundleId: 'com.example.personalTaskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzy8pBnnpTXAIFfbMyAfPr3zfh_YHcPxY',
    appId: '1:420842222143:ios:0a1a2ba98adadd4ea33e8a',
    messagingSenderId: '420842222143',
    projectId: 'task-ea0a9',
    storageBucket: 'task-ea0a9.appspot.com',
    iosBundleId: 'com.example.personalTaskManager.RunnerTests',
  );
}
